### ISSUE TITLE
Create invention disclosure.

### ISSUE THREAD

**Issue by mklingen** [personalrobotics/kinfu_ros#5]
Apparently all open repositories need an invention disclosure. Even though this is just a modification of another repository, this one needs an invention disclosure.

**Comment by psigen** [comment]
Is there some reference describing this policy? Perhaps we can document it for the others at the lab.

**Comment by siddhss5** [comment]
Clint has the correct policy. We do not need to disclose trivial things right? 

Sidd.

(Rapidly written in motion)

**Comment by mklingen** [comment]
Fair enough. I guess one way to disambiguate the policy would be to ignore forks of other people's repositories.
